name: CI
on:
  workflow_dispatch:
jobs:
  build:
    name: Build all
    runs-on: ubuntu-latest
    env:
      CMAKE_C_COMPILER: gcc
      CMAKE_CXX_COMPILER: g++
      CMAKE_ASM_COMPILER: as
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Change Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Downloads
        run: |
          sudo apt-get install -y ninja-build
          mkdir -p wasi-sdk
          cd scripts
          npm update
          node download_wasi_sdk.js
      - name: Build patched WASI-SDK
        run: ./build-wasi-sdk-new.sh
      - name: Build clang
        run: ./build-llvm.sh
      - name: Compile and run Hello World
        run: |
          cd test/
          node --version
          node --experimental-wasi-unstable-preview1 main.mjs || true
          node --experimental-wasi-unstable-preview1 main.mjs
